name: Check CHANGELOG

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🔍 Detect changes under src/
        id: check_diff
        run: |
          git fetch origin main --depth=1
          FILES=$(git diff --name-only origin/main...HEAD)
          echo "$FILES"

          if echo "$FILES" | grep -q '^src/'; then
            echo "src_changed=true" >> $GITHUB_OUTPUT
          else
            echo "src_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: 🛡 Require CHANGELOG.md update
        if: steps.check_diff.outputs.src_changed == 'true'
        run: |
          echo "Verifying CHANGELOG.md update..."
          if git diff --name-only origin/main...HEAD | grep -q '^CHANGELOG.md$'; then
            echo "✅ CHANGELOG.md was updated."
          else
            echo "❌ CHANGELOG.md was NOT updated. Please include your changes in it."
            exit 1
          fi
